apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  type: NodePort
  ports:
  - port: 9555
    targetPort: 9555
  selector:
    app: adservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - name: adservice
        image: folumii/adservice:latest
        ports:
        - containerPort: 9555
        env:
        - name: MESSAGE
          value: Hello from my first microservices deployment!

#### END of ADSERVICE ###
#------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: folumii/frontend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!
          
#### END of FRONTEND ###
#------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  type: LoadBalancer
  ports:
  - port: 7070
    targetPort: 7070
  selector:
    app: cartservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: adservice
        image: folumii/cartservice:latest
        ports:
        - containerPort: 7070
        env:
        - name: MESSAGE
          value: Hello from my first microservices front end deployment!    
          
 #### END of CARTSERVICE ###
#------------------------------------------------------------------------
